spring:
  application:
    name: platforms
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:platforms_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8082}
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8085}
users:
  service:
    url: ${USERS_SERVICE_URL:http://localhost:8081}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:11000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:platforms}