@url = {{host}}/auth

### LOGIN
POST {{url}}/login
Content-Type: application/json

{
  "email": "iXAmxzhE2WgLWB2VAEW@HuBhYZx.com",
  "password": "pa$$w0RD"
}

> {%
    const token = response.body.token
    const refreshToken = response.body.refreshToken
    client.global.set("token", token)
    client.global.set("refreshToken", refreshToken)
%}
