@url = {{host}}/admin/platform

### GET all plaftorms

GET {{url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpWEFteHpoRTJXZ0xXQjJWQUVXQEh1QmhZWnguY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NDczMDI0ODksImV4cCI6MTc0NzMwNjA4OX0.-d5WBf0aT4pjQQ9j8cP1EVQRKNEoKF7caJf_Ti-iJiw
### GET platform by id

GET {{url}}/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpWEFteHpoRTJXZ0xXQjJWQUVXQEh1QmhZWnguY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NDczMDI0ODksImV4cCI6MTc0NzMwNjA4OX0.-d5WBf0aT4pjQQ9j8cP1EVQRKNEoKF7caJf_Ti-iJiw

### POST new random platform

POST {{url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpWEFteHpoRTJXZ0xXQjJWQUVXQEh1QmhZWnguY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NDczMDI0ODksImV4cCI6MTc0NzMwNjA4OX0.-d5WBf0aT4pjQQ9j8cP1EVQRKNEoKF7caJf_Ti-iJiw
Content-Type: application/json

{
  "name": "{{$random.alphabetic(10)}}",
  "description": "{{$random.alphabetic(30)}}"
}

### DELETE platform by id

DELETE {{url}}/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpWEFteHpoRTJXZ0xXQjJWQUVXQEh1QmhZWnguY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NDczMDI0ODksImV4cCI6MTc0NzMwNjA4OX0.-d5WBf0aT4pjQQ9j8cP1EVQRKNEoKF7caJf_Ti-iJiw