@url = {{host}}/platform

### GET all plaftorms

GET {{url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpWEFteHpoRTJXZ0xXQjJWQUVXQEh1QmhZWnguY29tIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTc0NzIxODQzNywiZXhwIjoxNzQ3MjIyMDM3fQ.DXd2cgWzIR1cPV4_jCN_F0E-5mBk7-JuH0KJrqgfLpI

### GET platform by id

GET {{url}}/2

### POST new platform with random name

POST {{url}}
Content-Type: application/json

{
  "name": "{{$random.alphabetic(10)}}"
}

### DELETE platform by id

DELETE {{url}}/1